### ISSUE TITLE
library 7.0.10 version bad build

### ISSUE THREAD

**Issue by AlxZchk** [sclausen/ngx-mqtt#159]
@sclausen the 7.0.10 version doesn't work because of the bad build which currently looks like this. 
![bad-build](https://user-images.githubusercontent.com/42496999/90563787-f6d4ff00-e1ac-11ea-9688-a4392890a083.png)
how it should be:
![correct-build](https://user-images.githubusercontent.com/42496999/90563854-12400a00-e1ad-11ea-8667-620790e21de4.png)

It's caused by incorrect publish command. The right command was renamed to `publishx` in https://github.com/sclausen/ngx-mqtt/commit/623d5d506a2962a4f0a097c5815e9f5d53fb3469
You might want to revert that 🙂

**Comment by enlight3d** [comment]
Issues with latest version here too, I get "Cannot find module "ngx-mqtt" or its corresponding type declarations" since updating to v7.0.10

**Comment by sclausen** [comment]
v7.0.11 should've fixed the issue. sorry for any inconveniences.
