### ISSUE TITLE
5.0.8 nextTick error

### ISSUE THREAD

**Issue by reejinbouk** [sclausen/ngx-mqtt#64]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[+] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior

after upgrade from 5.0.6 to 5.0.8 got this error (used with ionic 3.9.2):
core.js:3683 Angular is running in the development mode. Call enableProdMode() to enable the production mode.
core.js:1448 ERROR Error: Uncaught (in promise): TypeError: nextTick is not a function
TypeError: nextTick is not a function
    at Object.generate [as writeToStream] (writeToStream.js:19)
    at sendPacket (client.js:37)
    at MqttClient._setupStream (client.js:286)
    at new MqttClient (client.js:227)
    at Function.connect (index.js:138)
    at MqttService.connect (mqtt.service.js:113)
    at new MqttService (mqtt.service.js:79)
    at mqttServiceFactory (app.module.ts:172)
    at _callFactory (core.js:10909)
    at _createProviderInstance$1 (core.js:10863)
    at Object.generate [as writeToStream] (writeToStream.js:19)
    at sendPacket (client.js:37)
    at MqttClient._setupStream (client.js:286)
    at new MqttClient (client.js:227)
    at Function.connect (index.js:138)
    at MqttService.connect (mqtt.service.js:113)
    at new MqttService (mqtt.service.js:79)
    at mqttServiceFactory (app.module.ts:172)
    at _callFactory (core.js:10909)
    at _createProviderInstance$1 (core.js:10863)
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.js:4736)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
defaultErrorLogger @ core.js:1448
ion-dev.js?v=3.1.8:120 Dev server logger closed
4livereload.js?snipver=1:74 WebSocket connection to 'ws://localhost:35729/livereload' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
exports.Connector.Connector.connect @ livereload.js?snipver=1:74
(anonymous) @ livereload.js?snipver=1:55
(anonymous) @ livereload.js?snipver=1:1152
t.invokeTask @ polyfills.js:3
r.runTask @ polyfills.js:3
e.invokeTask @ polyfills.js:3
i.isUsingGlobalCallback.invoke @ polyfills.js:3
n @ polyfills.js:3

## Environment

<pre><code>
ngx-mqtt version: 5.0.8

- Broker 

Others:

</code></pre>

**Comment by sclausen** [comment]
Could you please post your `package.json`?
